// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_application_1/test/adapter_pattern_example_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_application_1/design_patterns/structural/adapter_pattern_example.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MyAppMediaPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyAppMediaPlayer extends _i1.Mock implements _i2.MyAppMediaPlayer {
  @override
  void playMp3(String? fileName) => super.noSuchMethod(
    Invocation.method(#playMp3, [fileName]),
    returnValueForMissingStub: null,
  );

  @override
  void playMp4(String? fileName) => super.noSuchMethod(
    Invocation.method(#playMp4, [fileName]),
    returnValueForMissingStub: null,
  );
}
